// <auto-generated />
using LocalBusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessApiContext))]
    [Migration("20230401071351_UserClass")]
    partial class UserClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Name = "Blossoming Lotus"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Name = "Native Bowl"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Name = "Harlow"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Name = "Hail Snail"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Name = "Tiny Moreso"
                        });
                });

            modelBuilder.Entity("LocalBusinessApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Name = "Flutter"
                        },
                        new
                        {
                            ShopId = 2,
                            Name = "MadeHere"
                        },
                        new
                        {
                            ShopId = 3,
                            Name = "Tender Loving Empire"
                        },
                        new
                        {
                            ShopId = 4,
                            Name = "Blackthorn Mercantile"
                        },
                        new
                        {
                            ShopId = 5,
                            Name = "Made In Oregon"
                        });
                });

            modelBuilder.Entity("LocalBusinessApi.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
